Добавляет наставника
htmlacademy-htmlcss/2179843-sedona-35 pull request #1
Opened 2022-09-20 19:28 UTC by Yarik-333

Добавляет наставника.

2022-09-20 19:36 UTC, vadimrahmanov requested changes

2022-09-20 19:36 UTC, vadimrahmanov commented on Readme.md
> +* Наставник: `Вадим Рахманов` (https://htmlacademy.ru/profile/id1150187).
Имя необходимо вынести в квадратные скобки, также как твоё сверху. Может показаться, что это мелочь, но на самом деле в разработке очень важны такие мелочи. Где-то забыл запятую и весь код перестаёт работать)))

2022-09-22 08:23 UTC, Yarik-333 commented on Readme.md
> +* Наставник: `Вадим Рахманов` (https://htmlacademy.ru/profile/id1150187).
Понял, исправил

2022-09-22 10:41 UTC, vadimrahmanov approved these changes

2022-09-22 10:44 UTC, merged